Repository gardener/component-spec, pull requests merged in 2020-12, with the labels that each got.

#23 expose functions that are used in the component-cli
  bindings-go/apis/v2/accesstypes.go
  bindings-go/apis/v2/cdutils/utils.go
  bindings-go/apis/v2/componentdescriptor.go
  bindings-go/apis/v2/helper.go
  bindings-go/apis/v2/v2_suite_test.go
  bindings-go/apis/v2/validation/validation.go
  bindings-go/apis/v2/validation/validation_test.go
  bindings-go/ctf/componentarchive.go
  bindings-go/ctf/ctf.go
  bindings-go/oci/constants.go
  bindings-go/oci/manifest.go
  bindings-go/oci/resolve.go
Labels: needs/review, needs/second-opinion, size/xl

#24 fix extra identity getter for component references
  bindings-go/apis/v2/componentdescriptor.go
Labels: needs/review, size/xs

#25 deepcopy methods for component descriptor structs
  bindings-go/apis/v2/componentdescriptor.go
  bindings-go/apis/v2/zz_generated_deepcopy.go
  bindings-go/go.mod
  bindings-go/go.sum
  bindings-go/hack/boilerplate.go.txt
  bindings-go/hack/generate-code.sh
  bindings-go/hack/tools.go
Labels: needs/changes, size/l

#26 Prefix tags with 'v'
  VERSION
Labels: area/open-source, needs/review, size/xs

#28 Validate Parsed Component Descriptor
  bindings-python/gci/__init__.py
  bindings-python/gci/componentmodel.py
  bindings-python/setup.py
Labels: needs/changes, needs/review, size/s
