Repository gardener/component-spec, pull requests merged in 2020-11, with the labels that each got.

#12 oci mapping spec
  .gitignore
  bindings-python/gci/oci.py
  doc/.gitattributes
  doc/Blob.png
  doc/Build.png
  doc/index.rst
  doc/oci.rst
Labels: size/m

#15 Fix component encoding
  bindings-go/apis/v2/componentdescriptor.go
  bindings-go/codec/codec.go
  bindings-go/codec/codec_suite_test.go
Labels: size/xs

#14 convenience-getter for labels
  README.md
Labels: needs/review, size/xs

#17 add (optional) src-refs
  component-descriptor-v2-schema.yaml
Labels: size/xs

#18 extend github-access with optional attr `commit`
  component-descriptor-v2-schema.yaml
Labels: size/xs

#19 calculate identity
  bindings-python/gci/componentmodel.py
Labels: size/s

#21 add srcRefs-attr to python-bindings
  bindings-python/gci/componentmodel.py
Labels: size/xs

#22 Fix type of default value
  bindings-python/gci/componentmodel.py
Labels: needs/review, size/xs
