Repository gardener/component-spec, pull requests merged in 2021-06, with the labels that each got.

#38 Improve the repository context handling in the resolver
  bindings-go/apis/v2/accesstypes.go
  bindings-go/apis/v2/cdutils/utils.go
  bindings-go/apis/v2/componentdescriptor.go
  bindings-go/apis/v2/default.go
  bindings-go/apis/v2/helper.go
  bindings-go/apis/v2/list.go
  bindings-go/ctf/componentarchive.go
  bindings-go/ctf/ctf.go
  bindings-go/ctf/ctfutils/ctfutils.go
  bindings-go/go.mod
  bindings-go/go.sum
  bindings-go/oci/oci_suite_test.go
  bindings-go/oci/resolve.go
  bindings-go/oci/resolve_test.go
Labels: needs/review, needs/second-opinion, size/l

#39 adds new access type relativeOciReference
  bindings-go/apis/v2/accesstypes.go
  bindings-go/hack/install-requirements.sh
  bindings-python/gci/componentmodel.py
  bindings-python/tests/gci/componentmodel_test.py
  language-independent/test-resources/component_descriptor_v2_custom.yaml
Labels: needs/changes, needs/review, size/s

#40 Remove superfluous resource types
  bindings-python/gci/componentmodel.py
Labels: needs/review, size/xs

#42 implement new repository oci naming method
  bindings-go/Makefile
  bindings-go/README.md
  bindings-go/apis/v2/accesstypes.go
  bindings-go/apis/v2/cdutils/resources.go
  bindings-go/apis/v2/cdutils/utils.go
  bindings-go/apis/v2/codecs.go
  bindings-go/apis/v2/componentdescriptor.go
  bindings-go/apis/v2/default.go
  bindings-go/apis/v2/helper.go
  bindings-go/apis/v2/helper_test.go
  bindings-go/apis/v2/jsonscheme/bindata.go
  bindings-go/apis/v2/repositorytypes.go
  bindings-go/apis/v2/unstructured.go
  bindings-go/apis/v2/unstructured_test.go
  bindings-go/apis/v2/v2_suite_test.go
  bindings-go/apis/v2/validation/validation_test.go
  bindings-go/apis/v2/zz_generated_deepcopy.go
  bindings-go/ctf/componentarchive.go
  bindings-go/ctf/ctf.go
  bindings-go/ctf/ctfutils/ctfutils.go
  bindings-go/examples/custom/main.go
  bindings-go/examples/main.go
  bindings-go/go.mod
  bindings-go/go.sum
  bindings-go/hack/generate-code.sh
  bindings-go/oci/manifest.go
  bindings-go/oci/oci_suite_test.go
  bindings-go/oci/resolve.go
  bindings-go/oci/resolve_test.go
Labels: needs/review, needs/second-opinion, size/xl

#41 add optional component-name-mapping to repository-ctx
  doc/component_descriptor_registries.rst
  language-independent/component-descriptor-v2-schema.yaml
Labels: reviewed/lgtm, size/s
