Repository gardener/component-spec, pull requests merged in 2022-04, with the labels that each got.

#62 Rework CD section
  doc/proposal/00-overview.md
  doc/proposal/02-component-descriptor.md
  doc/proposal/04-local-blobs.md
  doc/proposal/app01-external-references.md
  doc/proposal/component-descriptor-v2-schema.yaml
  doc/proposal/in-progress/05-component-repository-oci.md
  doc/proposal/in-progress/06-local-references.md
  doc/proposal/in-progress/06-tranport-format.md
  doc/proposal/leftovers.md
Labels: needs/review, size/m

#64 Feedback for OCM Docu
  doc/proposal/01-introduction.md
  doc/proposal/04-local-blobs.md
  doc/proposal/leftovers.md
Labels: needs/review, size/xs

#65 OCM Docu feedback
  doc/proposal/leftovers.md
Labels: needs/review, size/xs

#63 Improvement of Signing/Verification
  bindings-go/apis/v2/componentdescriptor.go
  bindings-go/apis/v2/signatures/normalize.go
  bindings-go/apis/v2/signatures/normalize_test.go
  bindings-go/apis/v2/signatures/rsa.go
  bindings-go/apis/v2/signatures/sign_test.go
  bindings-go/apis/v2/signatures/types.go
  bindings-go/examples/signatures/main.go
Labels: needs/review, needs/second-opinion, size/l

#66 improved signature verification
  bindings-go/apis/v2/signatures/sign.go
Labels: needs/review, size/xs
