Repository gardener/component-spec, pull requests merged in 2022-03, with the labels that each got.

#59 Docu for OCM
  .gitignore
  README.md
  doc/proposal/00-overview.md
  doc/proposal/01-introduction.md
  doc/proposal/02-component-descriptor.md
  doc/proposal/03-component-repository.md
  doc/proposal/04-local-blobs.md
  doc/proposal/component-descriptor-v2-schema.yaml
  doc/proposal/images/component-artifact.png
  doc/proposal/images/component-repo.png
  doc/proposal/in-progress/04-type-definitions.md
  doc/proposal/in-progress/05-component-repository-oci.md
  doc/proposal/in-progress/06-tranport-format.md
  doc/proposal/leftovers.md
Labels: needs/review, needs/second-opinion, size/xl

#58 enhance signatures
  bindings-go/apis/v2/componentdescriptor.go
  bindings-go/apis/v2/signatures/rsa.go
  bindings-go/apis/v2/signatures/rsa_test.go
  bindings-python/gci/componentmodel.py
  language-independent/component-descriptor-v2-schema.yaml
Labels: needs/review, size/m

#60 Types in OCM
  doc/proposal/00-overview.md
  doc/proposal/03-component-repository.md
  doc/proposal/04-local-blobs.md
  doc/proposal/05-external-references.md
  doc/proposal/in-progress/04-type-definitions.md
  doc/proposal/in-progress/06-local-references.md
  doc/proposal/leftovers.md
Labels: reviewed/lgtm, size/m

#61 update signatures
  bindings-go/apis/v2/componentdescriptor.go
  bindings-go/apis/v2/signatures/rsa.go
  bindings-go/apis/v2/signatures/rsa_test.go
Labels: needs/review, size/s
