Repository gardener/component-spec, pull requests merged in 2022-05, with the labels that each got.

#67 adds cosign signature resource type
  bindings-go/apis/v2/resources.go
  bindings-python/gci/componentmodel.py
Labels: needs/review, size/xs

#70 Add signing fields to component descriptor schema
  doc/proposal/component-descriptor-v2-schema.yaml
Labels: reviewed/lgtm, size/s

#71 include version in identity of reference
  doc/proposal/02-component-descriptor.md
Labels: needs/review, size/xs

#73 Fix linter issue
  bindings-go/apis/v2/validation/validation_test.go
  bindings-go/apis/v2/zz_generated_deepcopy.go
Labels: size/xs

#74 integrate feedback from uwe
  doc/proposal/00-overview.md
  doc/proposal/01-introduction.md
  doc/proposal/02-component-descriptor.md
  doc/proposal/03-component-repository.md
  doc/proposal/04-local-blobs.md
  doc/proposal/app01-external-references.md
  doc/proposal/leftovers.md
Labels: needs/review, size/m
