Repository gardener/component-spec, pull requests merged in 2022-07, with the labels that each got.

#79 upgrade logr dependency
  bindings-go/apis/v2/zz_generated_deepcopy.go
  bindings-go/go.mod
  bindings-go/go.sum
  bindings-go/oci/resolve.go
Labels: needs/review, size/s

#68 Signing Spec
  doc/proposal/in-progress/07-signing.md
Labels: needs/changes, needs/review, size/m

#83 add exclude from signature digest to python binding
  bindings-python/gci/componentmodel.py
Labels: needs/review, size/xs
